### ISSUE TITLE
Question about generation narration texts

### ISSUE THREAD

**Issue by Versocial** [yukw777/EILEV#13]
what is the file ‘in_context_query_map_file’ for scripts/general/generate_narration_texts.py look like? I've got an error when trying to  make the generate_narration_texts.py work.

**Comment by Versocial** [comment]
my ‘in_context_query_map_file’ has 1line: ```{"context":["v_pYaJ7p8RrzM_seg_0_10_1","v_enG1CfTbT08_seg_55_65_4","v_emVaK5MoPBg_seg_75_85_2","v_emVaK5MoPBg_seg_15_25_2"],"query":"v_d4MZPbERTFs_seg_70_80_5"}```. each of the v_xxxxxxxx_seg_xx_xx_x is a video path in train/test dataset

**Comment by Versocial** [comment]
And I got this error:
```
Traceback (most recent call last):
  File "/home/whx/.conda/envs/vee/lib/python3.10/site-packages/accelerate/utils/operations.py", line 158, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
TypeError: BatchEncoding.to() got an unexpected keyword argument 'non_blocking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/whx/VEE/scripts/general/generate_narration_texts.py", line 259, in <module>
    eval(
  File "/root/autodl-tmp/whx/VEE/scripts/general/generate_narration_texts.py", line 113, in eval
    for i, datapoint in enumerate(tqdm(eval_dataloader, desc="Generating")):
  File "/home/whx/.conda/envs/vee/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/whx/.conda/envs/vee/lib/python3.10/site-packages/accelerate/data_loader.py", line 461, in __iter__
    current_batch = send_to_device(current_batch, self.device)
  File "/home/whx/.conda/envs/vee/lib/python3.10/site-packages/accelerate/utils/operations.py", line 160, in send_to_device
    return tensor.to(device)
  File "/home/whx/.conda/envs/vee/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 805, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/home/whx/.conda/envs/vee/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 805, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
AttributeError: 'list' object has no attribute 'to'
```

**Comment by yukw777** [comment]
Here's a snippet of an in-context query map file:

```
{"context": ["8f693e8a-5ea4-4b0f-93fd-787fe5f481df|78", "712ef11e-dc19-4fe1-ae66-0d9ec934196e|375", "c5c0dc6e-f414-490c-b9ec-1d36852e95d1|68", "fa21a282-6099-45cd-a4a7-39daf7973ec0|48"], "query": "570fc280-231c-4a3e-99c2-12eefed1c122|0"}
{"context": ["2763dbfc-8488-4264-b31f-4b12096c4c4b|36", "46fe43da-974a-4212-ad44-b98c30296909|30", "f7a0beb6-b220-40c0-a72d-ec4b79134a73|40", "b0429a48-6f89-4544-8128-a24fd63d3149|25"], "query": "3906d25a-d0a4-4a7c-8906-a87cea106c66|0"}
```

You can generate one using `scripts/general/sample_in_context_examples.py`.

**Comment by Versocial** [comment]
thanks
